### ISSUE TITLE
Parsing error: find measure fails

### ISSUE THREAD

**Issue by tilusnet** [MatthiasLienhard/flowkey_dl#19]
Getting 

```
Traceback (most recent call last):
  File "/home/tilushq/opt/miniconda3/envs/music/bin/flowkey-dl-cli", line 8, in <module>
    sys.exit(main())
  File "/home/tilushq/opt/miniconda3/envs/music/lib/python3.7/site-packages/flowkey_dl/flowkey_dl_cli.py", line 32, in main
    processed_image = arange_image(image, title, artist)
  File "/home/tilushq/opt/miniconda3/envs/music/lib/python3.7/site-packages/flowkey_dl/flowkey_dl.py", line 110, in arange_image
    measures = find_measure(image)
  File "/home/tilushq/opt/miniconda3/envs/music/lib/python3.7/site-packages/flowkey_dl/flowkey_dl.py", line 55, in find_measure
    measures = [positions[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

with `https://flowkeycdn.com/sheets/j5SxubMKcjBadtbFi/150/0.png` as input.

**Comment by MatthiasLienhard** [comment]
The method was confused by the horizontal line (8---------) in measure 4. It should work now with version 0.1.3.
