### ISSUE TITLE
Error when starting the script

### ISSUE THREAD

**Issue by REMberry** [MatthiasLienhard/flowkey_dl#9]
Hi, i try to use it on a windows computer. When i start the script, i get the following error:
flowkey-dl
Traceback (most recent call last):
  File "C:\Users\koege\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\koege\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\koege\anaconda3\Scripts\flowkey-dl.exe\__main__.py", line 4, in <module>
  File "C:\Users\koege\anaconda3\lib\site-packages\flowkey_dl\flowkey_dl_gui.py", line 6, in <module>
    from flowkey_dl import flowkey_dl, arange_image, save_png, save_pdf,strip_url
ImportError: cannot import name 'arange_image' from 'flowkey_dl' (C:\Users\koege\anaconda3\lib\site-packages\flowkey_dl\__init__.py)

**Comment by MatthiasLienhard** [comment]
Can you please try with the latest version?

**Comment by REMberry** [comment]
I tried and it worked now very well. thx.
